server:
  port: 8080

spring:
  application:
    name: consul-service
ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  restart:
    enabled: true
logging:
  level:
    org.springframework.cloud.consul: DEBUG