server:
  port: 8080

spring:
  application:
    name: consul-service
ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud.consul: DEBUG