logging:
  level:
    #        tk.mybatis: DEBUG
    com.micro.system: DEBUG
spring:
  application:
    name: micro-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:118.31.250.119}:${MYSQL_PORT:3306}/micro-admin-service?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root


mybatis:
  basepackage: com.micro.system.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 8082

