server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    database: 0
  application:
    name: micro-oauth
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:118.31.250.119}:${MYSQL_PORT:3306}/micro-admin-service?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: root


    mybatis:
      basepackage: com.micro.oauth.mapper
      xmlLocation: classpath:mapper/**/*.xml
      mapper-locations: "classpath*:mapper/*.xml"

logging:
  level:org.springframework: DEBUG

